name: flutter_app
description: social media app

version: 0.0.5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.11.1+6
  firebase_core: ^0.4.0+5
  firebase_database: ^3.0.2
  cloud_firestore: ^0.12.5
  firebase_storage: ^3.0.2
  firebase_performance: ^0.3.0+2
  flare_flutter: ^1.5.1
  google_sign_in: ^ 4.0.2
  connectivity: ^0.4.2
  shared_preferences: ^0.5.3+1
  flutter_datetime_picker: 1.2.8
  image_picker: ^0.6.0+2
  multi_image_picker: ^4.3.3
  curved_navigation_bar: ^0.2.20
  rounded_floating_app_bar: 0.1.0
  firebase_messaging: ^5.0.3
  device_info: any
  time_ago_provider: ^1.0.3
  transparent_image: ^0.1.0
  bottom_navy_bar: ^3.0.0
  location: ^2.3.5
  geolocator: ^5.0.1
  liquid_pull_to_refresh: ^1.1.1
  share: ^0.6.1+1
  pinch_zoom_image: any
  url_launcher: ^5.0.3
  image_cropper: ^1.0.2
  webview_flutter: ^0.3.9+1
  extended_image: any
  flutter_images_slider: ^0.0.2
  camera: ^0.5.2+1
  video_player: ^0.10.1+5






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - flar/progress.flr

    - flar/toggle.flr
    - flar/bob.flr
    - flar/login.flr
    - assets/indiz.png
    - assets/notification.png
    - assets/like.png
    - assets/icon.png
    - assets/profile.png
    - assets/chat.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
